#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Build using that tag name, plus an additional build arg.
gcloud builds submit --project plaidcloud-build \
  --config=cloud-build/$1.yaml \
  --machine-type=n1-highcpu-32 \
  --timeout=10000s \
  --substitutions=TAG_NAME="$2",_LAST_TAG="$(cat cloud-build/.$1.tmp)"

echo "$2" > cloud-build/.$1.tmp
