steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/superset-events:${_LAST_TAG} || exit 0
- name: "gcr.io/cloud-builders/docker"
  args: [
          "build",
          "-t", "us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/superset-events:${TAG_NAME}",
          "--file=Dockerfile.events",
          "--cache-from", "us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/superset-events:${_LAST_TAG}",
          "."
        ]
substitutions:
  _LAST_TAG: "latest"
images:
- "us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/superset-events:$TAG_NAME"
