# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
steps:
- name: 'gcr.io/cloud-builders/docker'
  env: 'DOCKER_BUILDKIT=1'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      mkdir tmp

      # (docker pull "us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/superset-py:$_LAST_TAG" && echo "$_LAST_TAG" > tmp/py) ||
      #   echo "latest" > tmp/py

      # docker build \
      #   -t us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/superset-py:$TAG_NAME \
      #   --cache-from us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/superset-py:$(cat tmp/py) \
      #   --target=superset-py \
      #   --build-arg PY_VER=3.11 \
      #   .

      (docker pull "us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/superset-node:$_LAST_TAG" && echo "$_LAST_TAG" > tmp/node) ||
        echo "latest" > tmp/node

      docker build \
        -t us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/superset-node:$TAG_NAME \
        --cache-from us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/superset-node:$(cat tmp/node) \
        --target=superset-node \
        --build-arg PY_VER=3.11 \
        .
substitutions:
  _LAST_TAG: "latest"
images:
- "us-docker.pkg.dev/plaidcloud-build/us-plaidcloud/superset-node:$TAG_NAME"
