devMode: false

spec:
  replicas: 1
  image: gcr.io/plaidcloud-build/superset/production:latest
  pullPolicy: Always
  imagePullSecret: gcr-key
  port: 80
  targetPort: 8088
  annotations: {}
  env:
    - name: SUPERSET_ENV
      value: "development"
    - name: SUPERSET_PORT
      value: "8088"

node:
  image: gcr.io/plaidcloud-build/superset/node:latest
  pullPolicy: Always
  imagePullSecret: gcr-key
  port: 80
  targetPort: 9000

superset_events:
  image: gcr.io/plaidcloud-build/superset/events:latest
  pullPolicy: Always
  imagePullSecret: gcr-key
  annotations: {}
  env:
    - name: SUPERSET_ENV
      value: "development"
    - name: HEADLESS
      value: "true"

ingress:
  enabled: true
  annotations: {}
  #   kubernetes.io/ingress.class: nginx
  hostname: "plaidcloud.io"
  tls: true
  tlsSecret: ingress-cert

database:
  user: superset
  pass: "strong superset password"
  host: superset-postgresql
  port: 5432
  name: superset
  greenplumHost: "127.0.0.1"

mapbox:
  apiKey: "pk.eyJ1IjoiZ2JhdGVzIiwiYSI6ImNqaGkwY25mZzIyZGczZG50MHpxMXk0bXYifQ.KKZQGn5QOn14NTnyNFNczQ"

oidc:
  baseUrl: "https://plaidcloud.io/"
  cookieName: "_session_id"
  clientId: ""
  clientSecret: ""
  authEndpoint: https://plaidcloud.io/oauth/authorize
  tokenEndpoint: https://plaidcloud.io/oauth/token
  jwksEndpoint: https://plaidcloud.io/oauth/jwks
  redirectUris:
  - https://viz.plaidcloud.io/oidc_callback
  
redis:
  enabled: true
  host: "redis-master"
  port: 26379
  group: "superset"
  cache_db: 14
  table_db: 15

rabbitmq:
  host: "rabbitmq-rabbitmq-ha"
  port: 5672
  username: "event_user"
  password: "event password"
  queue: "events"
  vhost: "events"
