apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: superset
  labels:
    app: plaid
    plaid: superset
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      name: superset-pod
      labels:
        app: plaid
        plaid: superset
    spec:
      containers:
      - name: superset
        image: docker.io/plaidcloud/superset:k8s
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
        - name: superset-conf
          mountPath: /etc/superset/
        - name: plaid-conf
          mountPath: /etc/plaid/
      imagePullSecrets:
      - name: dockerhub-key
      volumes:
      - name: superset-conf
        secret:
          secretName: superset-conf
      - name: plaid-conf
        secret:
          secretName: plaid-conf