apiVersion: v1
kind: Service
metadata:
  name: superset
  labels:
    app: plaid
    plaid: superset  
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    plaid: superset