apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: plaid
    plaid: superset
    release: {{ .Release.Name }}
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      name: superset
      labels:
        app: plaid
        plaid: superset
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: superset
        image: {{ .Values.superset.repo }}:{{ .Values.superset.tag }}
        imagePullPolicy: {{ .Values.superset.pullPolicy }}
        env:
{{ .Values.superset.env | toYaml | indent 10 }}
        ports:
        - name: http
          containerPort: 8088
        volumeMounts:
        - name: superset-conf
          mountPath: /etc/superset/
        resources: {}
      imagePullSecrets:
      - name: {{ .Values.superset.imagePullSecret }}
      volumes:
      - name: superset-conf
        configMap:
            name: {{ .Release.Name }}-config
