apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: plaid
    plaid: superset
    release: {{ .Release.Name }}
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      name: superset
      labels:
        app: plaid
        plaid: superset
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: superset
        image: {{ .Values.superset.image }}
        imagePullPolicy: {{ .Values.superset.pullPolicy }}
        {{- if .Values.superset.dev }}
        command: ["flask", "run", "-p", "8088", "--with-threads", "--reload", "--debugger", "--host=0.0.0.0"]
        {{- end }}
        env:
{{ .Values.superset.env | toYaml | indent 10 }}
        ports:
        - name: http
          containerPort: 8088
        volumeMounts:
        - name: superset-conf
          mountPath: /etc/superset/
        {{- if .Values.superset.dev }}      
        - name: static-assets
          mountPath: /app/superset/static/assets
        {{- end }}
        resources: {}
      {{- if .Values.superset.dev }}
      - name: node
        image: {{ .Values.node.image }}
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c", "cd /app/superset-frontend && npm ci && npm run build && npm run dev-server"]
        ports:
        - name: http
          containerPort: 9000
        volumeMounts:
        - name: static-assets
          mountPath: /app/superset/static/assets
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.superset.imagePullSecret }}
      volumes:
      - name: superset-conf
        configMap:
            name: {{ .Release.Name }}-config
      {{- if .Values.superset.dev }}
      - name: static-assets
        emptyDir: {}
      {{- end }}