apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-events
  labels:
    app: plaid
    plaid: superset-events
    release: {{ .Release.Name }}
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      name: superset
      {{- if .Values.superset_events.annotations }}
      annotations:
{{ toYaml .Values.superset_events.annotations | indent 8 }}
      {{- end }}
      labels:
        app: plaid
        plaid: superset-events
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: superset
        image: {{ .Values.superset_events.image }}
        imagePullPolicy: {{ .Values.superset_events.pullPolicy }}
        {{- if .Values.devMode }}
        command: ["watchmedo", "auto-restart", "-R",  "-p", "*.py", "python", "/plaid/plaid/event_handler.py"]
        {{- end }}
        env:
{{ .Values.superset_events.env | toYaml | indent 10 }}
        ports:
        - name: http
          containerPort: 8088
        volumeMounts:
        - name: superset-conf
          mountPath: /etc/superset/
        resources: {}
      imagePullSecrets:
      - name: {{ .Values.superset_events.imagePullSecret }}
      volumes:
      - name: superset-conf
        configMap:
            name: {{ .Release.Name }}-config
