apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: plaid
    plaid: superset
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.spec.replicas }}
  minReadySeconds: 10
  selector:
    matchLabels:
      app: plaid
      plaid: superset
      release: {{ .Release.Name }}
  template:
    metadata:
      name: superset
      {{- if .Values.spec.annotations }}
      annotations:
{{ toYaml .Values.spec.annotations | indent 8 }}
      {{- end }}
      labels:
        app: plaid
        plaid: superset
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: superset
        image: {{ .Values.spec.image }}
        imagePullPolicy: {{ .Values.spec.pullPolicy }}
        {{- if .Values.devMode }}
        command: ["sleep", "infinity"]
        # command: ["flask", "run", "-p", "8088", "--with-threads", "--reload", "--debugger", "--host=0.0.0.0"]
        {{- end }}
        env:
{{ .Values.spec.env | toYaml | indent 10 }}
        ports:
        - name: http
          containerPort: 8088
        volumeMounts:
        - name: superset-conf
          mountPath: /etc/superset/
        {{- if .Values.devMode }}      
        - name: static-assets
          mountPath: /app/superset/static/assets
        {{- end }}
        resources: {}
      {{- if .Values.devMode }}
      - name: node
        image: {{ .Values.node.image }}
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c", "cd /app/superset-frontend && npm ci && npm run build-dev && npm run dev-server"]
        ports:
        - name: http
          containerPort: 9000
        volumeMounts:
        - name: static-assets
          mountPath: /app/superset/static/assets
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.spec.imagePullSecret }}
      volumes:
      - name: superset-conf
        configMap:
            name: {{ .Release.Name }}-config
      {{- if .Values.devMode }}
      - name: static-assets
        emptyDir: {}
      {{- end }}
