apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      if ( $http_x_forwarded_proto != 'https' ) {
        return 307 https://$host$request_uri;
      }

  name: {{ .Release.Name }}
  labels:
    app: plaid
    plaid: superset
    release: {{ .Release.Name }}
spec:
  rules:
  {{- if .Values.devMode }}
  - host: {{ .Release.Namespace }}-viz.plaidcloud.io
  {{- else }}
  - host: {{ .Values.superset.hostname }}
  {{- end }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.superset.port }}
