{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  {{- end }}
  name: {{ .Release.Name }}
  labels:
    app: plaid
    plaid: plaid
    release: {{ .Release.Name }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  rules:
  {{- if .Values.devMode }}
  - host: {{ .Release.Namespace }}.plaidcloud.io
  {{- else }}
  - host: {{ .Values.ingress.hostname }}
  {{- end }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.superset.port }}
{{- end }}
