apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: plaid
    plaid: superset
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.superset.port }}  
    {{- if .Values.devMode }}
    targetPort: {{ .Values.node.targetPort }}
    {{- else }}
    targetPort: {{ .Values.superset.targetPort }}  
    {{- end }}
    protocol: TCP
    name: http
  selector:
    plaid: superset
    release: {{ .Release.Name }}
