apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: plaid
    plaid: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.superset.port }}  
    targetPort: {{ .Values.superset.targetPort }}  
    protocol: TCP
    name: http
  selector:
    plaid: superset
    release: {{ .Release.Name }}
